Fixes from code review of /etc/init.d scripts: > /etc/init.d/lockss: > > - Should support "restart" argument. Done. > > /etc/lockss/startdaemon: > > - Move is_secure to functions can't - need it to decide if "functions" is secure. > - Use find instead of ls Done > - Test at line 21 should be -f not -x Done. > - Adding /usr/xpg4/bin to path should be Solaris only Done. > - Comment at line 38 should explicitly say variables exported There are 24 of them currently and this changes,  don't think this is practical > - Setting RUN_SSL at line 76 should ensure in 2-user case scripts have > different names (i.e. neither default to /etc/lockss/runssl) Hard to do because startdaemon does not know whether it is in the 2-daemon or 1-daemon case. > > /etc/lockss/rundaemon: > > - LOCKSS_HOME support for unprivileged install should be removed once > we determine that no more Solaris 9 boxes exist Postponed > - Line 19 put braces round 1 Done > - Line 20 should shift in loop, then refer to ${1} not ${2} Done > - Code should count number of daemon restarts and only exit without > restarting daemon if more than N restarts in M seconds. XXX > - Code at line 121 limits number of daemons to 2 - fix it. Done > - Move setting of {MIN,MAX}_JAVA_HEAP to head of file Done > - Java heap setting code should be in functions Done > - Code at line 152 should not source CFG_FILE but use sed. This code > should be in functions. There are quoting issues that mean this code isn't the same, but I have prevented CFG_FILE being sourced > - Investigate issue of quoting @CLASSPATH@ and similar parameters XXX
> - Line 170 default heap size should be DEFAULT_JAVA_HEAP
Done
> - Line 174 there is a bug here - use case statement instead of if
Done
> - Line 185 default test group should be DEFAULT_TEST_GROUP
Done
> - Line 193 use case statement instead of if, make "yes" case-insensitive
Done
> - Line 200 daemon should delete tree resulting from unzip of file
XXX
> - Line 204 check that here documents do not expand globs
They don't
> - Line 223 check effect of trailing slash
Its gone
> - Determine whether this code prevents daemon restarting after quick
> death. If it does, this needs to be fixed back to previous behavior
> for 1.48.
Done for 1.48
>
> /etc/lockss/runssl:
>
> - Move is_secure to functions. Either merge with other is_secure or
> rename.
Done
> - Exit if not running as root
Always did, new explicit test added
> - There should be one keystore dir per user
There can now be one public keystore per user. There has always been one
private store per LOCKSS_HOSTNAME, which can be different between
different users on the same host provided DNS maps to the same IP
address.
> - Line 28 use "$@" not $*
Done
> - Check RUN_DIR, exit if not set, verify correct owner, permission
Done
> - Line 84 kill -9
Done
> - Line 117 second rm -f redundant
Done
> - PID file only needed by root - should not be in TEMP_DIR
>
> /etc/lockss/functions:
>
> - Is use of /usr/bin/bash on Solaris OK?
Fixed by TAL for 1.48
> - Check behavior of set_variables() if no args
Fixed
> - Check behavior if e.g. user name is "root"
Fixed
> - Line 126 check list of variables unset
Checked


git-svn-id: svn://svn.code.sf.net/p/lockss/svn/lockss-daemon/trunk@11036 4f837ed2-42f5-46e7-a7a5-fa17313484d4

diff --git a/rpms/BUILD/lockss-daemon-root/etc/init.d/lockss b/rpms/BUILD/lockss-daemon-root/etc/init.d/lockss
--- a/rpms/BUILD/lockss-daemon-root/etc/init.d/lockss
+++ b/rpms/BUILD/lockss-daemon-root/etc/init.d/lockss
@@ -16,45 +16,57 @@ then
 fi
 case "$1" in
     start)
-        if [ ! -r ${CFG_FILE} ]; then
-            echo "Can't start ${2}: ${CFG_FILE} missing or not readable"
-            exit 1
-        fi
-        if [ ! -d ${LOG_DIR} ]; then
-            mkdir -p ${LOG_DIR}
-            chown $2 ${LOG_DIR}
-            chmod 755 ${LOG_DIR}
-        fi
-        if [ ! -f ${PID_FILE} ]; then
-            touch ${PID_FILE}
-        fi
-        chown $2 ${PID_FILE}
-        chmod 644 ${PID_FILE}
-        echo -n "Starting ${2}: "
-        echo "Starting LOCKSS for user $2 at `date`" >> ${LOG_FILE}
-        chown $2 ${LOG_FILE}
-        daemon /etc/lockss/startdaemon $2
-        echo
+	start_lockss ${2}
         ;;
     stop)
-        echo -n "Stopping ${2}: "
-        rm -f "${KEEP_GOING}"
-        killproc $2
-        rm -f ${PID_FILE} ${RUN_DIR}/${2}-ssl.pid
-        echo
+        stop_lockss ${2}
         ;;
+    restart)
+	stop_lockss ${2}
+	start_lockss ${2}
+	;;
     *)
-        echo "Usage: $0 {start|stop}"
+        echo "Usage: $0 {start|stop|restart}"
         exit 1
         ;;
 esac
+}
+
+stop_lockss () {
+    echo -n "Stopping ${1}: "
+    rm -f "${KEEP_GOING}"
+    killproc ${1}
+    rm -f ${PID_FILE} ${RUN_DIR}/${1}-ssl.pid
+    echo
+}
+
+start_lockss () {
+    if [ ! -r ${CFG_FILE} ]; then
+        echo "Can't start ${1}: ${CFG_FILE} missing or not readable"
+        exit 1
+    fi
+    if [ ! -d ${LOG_DIR} ]; then
+        mkdir -p ${LOG_DIR}
+        chown ${1} ${LOG_DIR}
+        chmod 755 ${LOG_DIR}
+    fi
+    if [ ! -f ${PID_FILE} ]; then
+        touch ${PID_FILE}
+    fi
+    chown ${1} ${PID_FILE}
+    chmod 644 ${PID_FILE}
+    echo -n "Starting ${1}: "
+    echo "Starting LOCKSS for user ${1} at `date`" >> ${LOG_FILE}
+    chown ${1} ${LOG_FILE}
+    daemon /etc/lockss/startdaemon ${1}
+    echo
 }
 
 set_lockss_user
 for A in ${LOCKSS_USER}
 do
         set_variables ${A}
-        do_command $1 $A
+        do_command ${1} $A
         unset_variables
 done
 
