Changes from Issue 3083 code review: - indentation cleanup -t to 8 spaces - comment in runssl needs fix because we now copy password and keystore - check of owner/permission in runssl should be function - runssl:97 LOCKSS_USER not lockss - runssl:113 name of public keystore should be fixed and .jceks - startdaemon - remove all LOCKSS_HOME support and HOME support - startdaemon:54 - chown root
git-svn-id: svn://svn.code.sf.net/p/lockss/svn/lockss-daemon/trunk@9678 4f837ed2-42f5-46e7-a7a5-fa17313484d4

diff --git a/rpms/BUILD/lockss-daemon-root/etc/init.d/lockss b/rpms/BUILD/lockss-daemon-root/etc/init.d/lockss
--- a/rpms/BUILD/lockss-daemon-root/etc/init.d/lockss
+++ b/rpms/BUILD/lockss-daemon-root/etc/init.d/lockss
@@ -12,41 +12,41 @@
 do_command () {
 if [ -f ${LOCKSS_HOME}/config.$2.dat ]
 then
-	${CFG_FILE}=${LOCKSS_HOME}/config.$2.dat
+        ${CFG_FILE}=${LOCKSS_HOME}/config.$2.dat
 fi
 case "$1" in
     start)
-	if [ ! -r ${CFG_FILE} ]; then
-	    echo "Can't start ${2}: ${CFG_FILE} missing or not readable"
-	    exit 1
-	fi
-	if [ ! -d ${LOG_DIR} ]; then
-	    mkdir -p ${LOG_DIR}
-	    chown $2 ${LOG_DIR}
-	    chmod 755 ${LOG_DIR}
-	fi
-	if [ ! -f ${PID_FILE} ]; then
-	    touch ${PID_FILE}
-	fi
-	chown $2 ${PID_FILE}
-	chmod 644 ${PID_FILE}
-	echo -n "Starting ${2}: "
-	echo "Starting LOCKSS for user $2 at `date`" >> ${LOG_FILE}
-	chown $2 ${LOG_FILE}
-	daemon /etc/lockss/startdaemon $2
-	echo
-	;;
+        if [ ! -r ${CFG_FILE} ]; then
+            echo "Can't start ${2}: ${CFG_FILE} missing or not readable"
+            exit 1
+        fi
+        if [ ! -d ${LOG_DIR} ]; then
+            mkdir -p ${LOG_DIR}
+            chown $2 ${LOG_DIR}
+            chmod 755 ${LOG_DIR}
+        fi
+        if [ ! -f ${PID_FILE} ]; then
+            touch ${PID_FILE}
+        fi
+        chown $2 ${PID_FILE}
+        chmod 644 ${PID_FILE}
+        echo -n "Starting ${2}: "
+        echo "Starting LOCKSS for user $2 at `date`" >> ${LOG_FILE}
+        chown $2 ${LOG_FILE}
+        daemon /etc/lockss/startdaemon $2
+        echo
+        ;;
     stop)
-	echo -n "Stopping ${2}: "
-	rm -f "${KEEP_GOING}"
-	killproc $2
-	rm -f ${PID_FILE} ${RUN_DIR}/${2}-ssl.pid
-	echo
-	;;
+        echo -n "Stopping ${2}: "
+        rm -f "${KEEP_GOING}"
+        killproc $2
+        rm -f ${PID_FILE} ${RUN_DIR}/${2}-ssl.pid
+        echo
+        ;;
     *)
-	echo "Usage: $0 {start|stop}"
-	exit 1
-	;;
+        echo "Usage: $0 {start|stop}"
+        exit 1
+        ;;
 esac
 }
 
@@ -55,7 +55,7 @@ for A in ${LOCKSS_USER}
 do
         set_variables ${A}
         do_command $1 $A
-	unset_variables
+        unset_variables
 done
 
 
