Output the useful error message to stderr instead.

diff --git a/scripts/tdb/tdbout b/scripts/tdb/tdbout
--- a/scripts/tdb/tdbout
+++ b/scripts/tdb/tdbout
@@ -1,7 +1,7 @@
 #!/bin/sh
 CLASSPATHFILE=test/run-classpath
 if [ ! -f $CLASSPATHFILE ]; then
-  echo "${CLASSPATHFILE} not found; run from root of project after ant jar-lockss"
+  echo "${CLASSPATHFILE} not found; run from root of project after ant jar-lockss" >&2
   exit 1
 fi
 if [ "X${JAVA_HOME}" = "X" ]; then
