Switch to the new TDB tools.
git-svn-id: svn://svn.code.sf.net/p/lockss/svn/lockss-daemon/trunk@37642 4f837ed2-42f5-46e7-a7a5-fa17313484d4

diff --git a/scripts/tdb/tdbxml b/scripts/tdb/tdbxml
--- a/scripts/tdb/tdbxml
+++ b/scripts/tdb/tdbxml
@@ -1,4 +1,12 @@
-#!/bin/bash
-
-DIRECTORY=$(cd `dirname $0` && pwd)
-python $DIRECTORY/tdbxml.py "$@"
+#!/bin/sh
+CLASSPATHFILE=test/run-classpath
+if [ ! -f $CLASSPATHFILE ]; then
+  echo "${CLASSPATHFILE} not found; run from root of project after ant jar-lockss"
+  exit 1
+fi
+if [ "X${JAVA_HOME}" = "X" ]; then
+  JAVA=java
+else
+  JAVA=$JAVA_HOME/bin/java
+fi
+$JAVA -classpath `cat $CLASSPATHFILE` org.lockss.tdb.TdbXml "$@"
