Don't test java version before LOCKSS_JAVA_CMD set.
git-svn-id: svn://svn.code.sf.net/p/lockss/svn/lockss-daemon/trunk@9146 4f837ed2-42f5-46e7-a7a5-fa17313484d4

diff --git a/rpms/BUILD/lockss-daemon-root/etc/lockss/rundaemon b/rpms/BUILD/lockss-daemon-root/etc/lockss/rundaemon
--- a/rpms/BUILD/lockss-daemon-root/etc/lockss/rundaemon
+++ b/rpms/BUILD/lockss-daemon-root/etc/lockss/rundaemon
@@ -16,17 +16,6 @@ else
         exit 1
 fi
 
-JAVA_VERSION=`${LOCKSS_JAVA_CMD} -version 2>&1 | head -1 | sed -e 's/.* "\(.*\)"/\1/'`
-case "X${JAVA_VERSION}" in
-X1.[6789]*)
-	;;
-*)
-	echo "Java version is ${JAVA_VERSION}: 1.6 or higher required"
-	exit 1
-	;;
-esac
-
-
 if [ "X$1" = Xwait ]; then
     WAIT=Y
 fi
@@ -78,6 +67,16 @@ else
   echo "${CFG_FILE} missing; run ${CFG_SCRIPT}"
   exit 1
 fi
+
+JAVA_VERSION=`${LOCKSS_JAVA_CMD} -version 2>&1 | head -1 | sed -e 's/.* "\(.*\)"/\1/'`
+case "X${JAVA_VERSION}" in
+X1.[6789]*)
+	;;
+*)
+	echo "Java version is ${JAVA_VERSION}: 1.6 or higher required"
+	exit 1
+	;;
+esac
 
 CLASSPATH=@CLASSPATH@
 DAEMON_CLASS=org.lockss.app.LockssDaemon
