Restored LCAP SSL functionality. Disabled broken test for running as root.
git-svn-id: svn://svn.code.sf.net/p/lockss/svn/lockss-daemon/trunk@12040 4f837ed2-42f5-46e7-a7a5-fa17313484d4

diff --git a/rpms/BUILD/lockss-daemon-root/etc/lockss/runssl b/rpms/BUILD/lockss-daemon-root/etc/lockss/runssl
--- a/rpms/BUILD/lockss-daemon-root/etc/lockss/runssl
+++ b/rpms/BUILD/lockss-daemon-root/etc/lockss/runssl
@@ -24,6 +24,14 @@ for ARG in $@ ; do
     esac
     shift
 done
+
+if [ -f ${LOCKSS_HOME}/etc/lockss/functions ] ; then
+    . ${LOCKSS_HOME}/etc/lockss/functions
+else
+    echo "Can't find LOCKSS functions"
+    exit 1
+fi
+
 # If no LOCKSS_SSL_CONFIG then SSL not in use
 if [ "${LOCKSS_SSL_CONFIG}X" = X ]; then
     exit 0
@@ -63,10 +71,10 @@ if [ "X${CFG_FILE}" = X ]; then
     echo "WARNING: no CFG_FILE"
     exit 1
 fi
-if [ X`find ${CFG_FILE} -writable` != X${CFG_FILE} ]; then
-    echo "Not running as root"
-    exit 1
-fi
+#if [ X`find ${CFG_FILE} -writable` != X${CFG_FILE} ]; then
+#    echo "Not running as root"
+#    exit 1
+#fi
 LOCKSS_HOSTNAME=`sed -n 's/LOCKSS_HOSTNAME=//p' ${CFG_FILE}`
 if [ "X${LOCKSS_HOSTNAME}" = X ]; then
     echo "WARNING: host name not configured"
